# FROM ubuntu:latest
# # MAINTAINER SteveLee "lclgood@khu.ac.kr"
# RUN apt-get update
# RUN apt-get install -y nginx
# RUN echo "this is a ubuntu container"
# WORKDIR /etc/nginx
# CMD ["nginx", "-g", "daemon off;"]
# EXPOSE 80

FROM busybox:latest
MAINTAINER SteveLee "lclgood@khu.ac.kr"
RUN echo "this is busybox"