# FROM python:3
# ENV PYTHONUNBUFFERED 1
# WORKDIR /web
# COPY . .
# RUN pip install -r requirements.txtim

# FROM ubuntu:latest
# # MAINTAINER SteveLee "lclgood@khu.ac.kr"
# RUN apt-get update
# RUN apt-get install -y nginx
# RUN echo "this is a ubuntu container"
# WORKDIR /etc/nginx
# CMD ["nginx", "-g", "daemon off;"]
# EXPOSE 80